config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'tops#index'

  get 'tops/index'
  get 'webpages/index'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy, :index]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, length: { in: 1..140 }
    validates :content, length: { in: 1..140 }

    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user

    mount_uploader :image, ImageUploader
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord


  validates :name, presence: true, length:{maximum: 30}
  validates :email, presence: true, length:{maximum: 255},
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_save {email.downcase!}
  has_secure_password
  # validates :password, presence: true, length: {minimum: 6}

  has_many :blogs

  has_many :favorites, dependent: :destroy

  has_many :favorite_blogs, through: :favorites, source: :blog

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
     before_action :set_blog, only: [:show, :edit, :update, :destroy]
     before_action :login_redirect, only: [:new, :edit, :show, :destroy]

    def index
        @blogs = Blog.all
    end

    def new
        if params[:back]
            @blog = Blog.new(blog_params)
        else
            @blog = Blog.new
        end
    end

    def create
        # binding.pry
        @blog = Blog.new(blog_params)
        # @blog.user_id = current_user.id

        if @blog.save
        # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
            BlogPostMailer.blog_post_mail(@blog).deliver
            redirect_to blogs_path, notice: "ブログを作成しました！"

        else

        # 入力フォームを再描画します。
            render 'new'
        end

    end

    def edit

    end

    def show
        # binding.pry
        @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end

    def destroy
        @blog.destroy
        redirect_to blogs_path, notice:"ブログを削除しました！"
    end

    def update
        # binding.pry
        @blog = Blog.find(params[:id])
        if @blog.update(blog_params)
            redirect_to blogs_path, notice: "ブログを編集しました！"
        else
            render 'edit'
        end
    end

    def confirm
        # binding.pry
        @blog = Blog.new(blog_params)
        # @blog.user_id = current_user.id
        render :new if @blog.invalid?
    end

    def login_redirect
        unless logged_in?
            redirect_to root_path, notice: "閲覧権限がありません。トップページにリダイレクトしました。"
        end
    end

    private
    def blog_params
        params.require(:blog).permit(:title, :content, :image).merge(user_id: current_user.id)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    # binding.pry
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end

  def index
    # binding.pry
    @favorite_blogs = current_user.favorite_blogs
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&& user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました。"
    redirect_to new_session_path
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path, notice: "Sign upを完了しました。ログインしてください。"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    # binding.pry
    @user = User.find(params[:id])
  end

  def update
    # binding.pry
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(current_user.id), notice: "マイページを編集しました！"
    else
        redirect_to user_path(current_user.id)
        # render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/controllers/webpages_controller.rb
class WebpagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webpages_helper.rb
module WebpagesHelper
end

app/views/blogs/_form.html.erb
<div class="form-area">

<%= form_with(model: @blog, local: true ) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <div><%= form.label :title %></div>
    <div class=" form-width"><%= form.text_field :title %></div>
  </div>
  <div class="blog_title">
    <div><%= form.label :content %></div>
    <div class=" form-width"><%= form.text_field :content %></div>
  </div>

  <div>
     <p class="text-center"><%= form.file_field :image %></p>
  </div>

  <div class=" form-width btn-margin">
    <%= form.submit :class => "btn btn-success" %>
  </div>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

</div>

app/views/blogs/confirm.html.erb
<h3>投稿確認画面</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>イメージ:<%= @blog.image %></p>
  <%= form.submit  "登録する", class: "btn btn-success" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.submit "もどる", name: 'back', class: "btn btn-default "%>
<% end %>

app/views/blogs/edit.html.erb
<h1>ブログ編集</h1>

<%= form_with(model: @blog, local: true) do |form| %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <p class="text-center"><%= form.file_field :image %></p>
  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<h1>Listing Blogs</h1>

<div class="container">
  <div id="new-blog-link">
    <%= link_to '新規ブログを作成する', new_blog_path %>
  </div>

  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-xs-12 col-md-6 blog-panel">

        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= image_tag blog.image.url(:thumb) if blog.image? %></p>
        <p><%= blog.created_at %></p>
        <div class="blog-links">
          <%= link_to 'Show', blog, class: 'btn btn-default' %>
          <% if blog.user == current_user %>
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-info' %> |
          <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div></div>
</div>

app/views/blogs/new.html.erb
<h1>ブログ投稿</h1>

 <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<%= link_to "投稿一覧に戻る", blogs_path, class: 'btn btn-default' %>

<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-prymary' %>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <p>Made By YO</p>
</footer>

app/views/common/_header.html.erb
<nav class="navbar navbar-inverse">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h3><%= link_to "DIC BootStrap Series2", root_path %></a></h3>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "トップページ", root_path %></li>
        <li><%= link_to "投稿一覧", blogs_path, method: :get %></li>
        <li><%= link_to "新規投稿", new_blog_path, method: :get %></li>
        <li><%= link_to "マイページ", user_path(current_user.id), method: :get if logged_in? %></li>
        <li><%= link_to "webpage_index", webpages_index_path, method: :get %></li>
        <li><%= link_to "お気に入り一覧", favorites_path, method: :get %></li>
        <% unless logged_in? %>
        <li><%= link_to "Log in", new_session_path, method: :get %></li>
        <li><%= link_to "Sign up", new_user_path, method: :get %></li>
        <% end %>
        <% if logged_in? %>
        <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>

</nav>

app/views/favorites/index.html.erb
<h1>Listing Blogs</h1>

<div class="container">

  <div class="row">
    <% @favorite_blogs.each do |blog| %>
      <div class="col-xs-12 col-md-6 blog-panel">
        <h2><%= blog.title %></h2>
        <p><%= blog.content %></p>
        <p><%= blog.created_at %></p>
        <div class="blog-links">
          <%= link_to 'Show', blog, class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HerokuTestApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "common/header" %>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

    <%= render partial: "common/footer" %>

  </body>
</html>

app/views/tops/index.html.erb
  <section class="main-header">
    <%= image_tag "achieve.png", class: "text-center" %>
  </section>
  <section class="about">
    <h1>DIC BootStrap Series2</h1>
    <p>
      DIC BootStrap Series2はBootStrapシリーズ課題2を作成したものです。
    </p>
    <p>
      Railsを使用しており、BootStrapと少々の独自CSSを当てて作成されています。
    </p>
  </section>
  <section class="function">
    <h1>Function</h1>
    <div class="function-images row">
      <div class="function-image col-xs-12 col-sm-6 col-md-3">
        <%= image_tag "key.png" %>
        <p>ログイン機能</p>
      </div>
      <div class="function-image col-xs-12 col-sm-6 col-md-3">
      <%= image_tag "mails.png" %>
        <p>メール送信機能</p>
      </div>
      <div class="function-image col-xs-12 col-sm-6 col-md-3">
        <%= image_tag "girls.png" %>
        <p>友達つながり機能</p>
      </div>
      <div class="function-image col-xs-12 col-sm-6 col-md-3">
        <%= image_tag "comment.png" %>
        <p>コメント投稿機能</p>
      </div>
    </div>
  </section>

</body>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.label :image %></p>
  <p class="text-center"><%= f.file_field :image %></p>

  <p><%= f.submit "編集", class: "btn btn-success" %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account", class: "btn btn-success" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<% if logged_in? %>
<p><%= link_to "編集", edit_user_path(current_user.id), method: :get %></p>
<% end %>

<p><%= image_tag @user.image.url(:thumb) if @user.image? %></p>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>

app/views/webpages/index.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "tcr_s.jpg" %>
      <div class="caption">
        <h3>Thumbnail label 1</h3>
        <ul class="list-unstyled">
            <li>contents1</li>
            <li>contents2</li>
            <li>contents3</li>
            <li>contents4</li>
        </ul>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "tcr_s.jpg" %>
      <div class="caption">
        <h3>Thumbnail label 2</h3>
        <ul class="list-unstyled">
            <li>contents1</li>
            <li>contents2</li>
            <li>contents3</li>
            <li>contents4</li>
        </ul>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "tcr_s.jpg" %>
      <div class="caption">
        <h3>Thumbnail label 3</h3>
        <ul class="list-unstyled">
            <li>contents1</li>
            <li>contents2</li>
            <li>contents3</li>
            <li>contents4</li>
        </ul>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>



</div>